// <auto-generated />
using System;
using BeYou.Infraestructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BeYou.Infraestructure.Migrations
{
    [DbContext(typeof(BeYouContext))]
    partial class BeYouContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BeYou.Domain.Models.Branch", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Address")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<long>("DistrictId")
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("Telephone")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "DistrictId" }, "IX_Branch_DistrictId");

                    b.ToTable("Branch", (string)null);
                });

            modelBuilder.Entity("BeYou.Domain.Models.BranchHoliday", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<long>("HolidayId")
                        .HasColumnType("bigint");

                    b.Property<short>("Year")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "BranchId" }, "IX_BranchHoliday_BranchId");

                    b.HasIndex(new[] { "HolidayId" }, "IX_BranchHoliday_HolidayId");

                    b.ToTable("BranchHoliday", (string)null);
                });

            modelBuilder.Entity("BeYou.Domain.Models.BranchSchedule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint");

                    b.Property<long>("ScheduleId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "BranchId" }, "IX_BranchSchedule_BranchId");

                    b.HasIndex(new[] { "ScheduleId" }, "IX_BranchSchedule_ScheduleId");

                    b.ToTable("BranchSchedule", (string)null);
                });

            modelBuilder.Entity("BeYou.Domain.Models.BranchScheduleBlock", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<long>("BranchScheduleId")
                        .HasColumnType("bigint");

                    b.Property<TimeOnly>("EndHour")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("StartHour")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "BranchScheduleId" }, "IX_BranchScheduleBlock_BranchSchedule");

                    b.ToTable("BranchScheduleBlock", (string)null);
                });

            modelBuilder.Entity("BeYou.Domain.Models.Canton", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("ProvinceId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ProvinceId" }, "IX_Canton_ProvinceId");

                    b.ToTable("Canton", (string)null);
                });

            modelBuilder.Entity("BeYou.Domain.Models.Category", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("Id");

                    b.ToTable("Category", (string)null);
                });

            modelBuilder.Entity("BeYou.Domain.Models.Contact", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("Telephone")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<long>("VendorId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "VendorId" }, "IX_Contact_VendorId");

                    b.ToTable("Contact", (string)null);
                });

            modelBuilder.Entity("BeYou.Domain.Models.Customer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Address")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<long>("DistrictId")
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("Telephone")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "DistrictId" }, "IX_Customer_DistrictId");

                    b.ToTable("Customer", (string)null);
                });

            modelBuilder.Entity("BeYou.Domain.Models.District", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CantonId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CantonId" }, "IX_District_CantonId");

                    b.ToTable("District", (string)null);
                });

            modelBuilder.Entity("BeYou.Domain.Models.Gender", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.ToTable("Gender", (string)null);
                });

            modelBuilder.Entity("BeYou.Domain.Models.Holiday", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<byte>("Day")
                        .HasColumnType("tinyint");

                    b.Property<string>("Month")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("Id");

                    b.ToTable("Holiday", (string)null);
                });

            modelBuilder.Entity("BeYou.Domain.Models.Inventory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeInventory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "BranchId" }, "IX_Inventory_BranchId");

                    b.ToTable("Inventory", (string)null);
                });

            modelBuilder.Entity("BeYou.Domain.Models.InventoryProduct", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<decimal>("Assignable")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<long>("IdProducto")
                        .HasColumnType("bigint");

                    b.Property<long>("InventoryId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Maximum")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Mininum")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "IdProducto" }, "IX_InventoryProduct_IdProducto");

                    b.HasIndex(new[] { "InventoryId" }, "IX_InventoryProduct_InventoryId");

                    b.HasIndex(new[] { "ProductId" }, "IX_InventoryProduct_ProductId");

                    b.ToTable("InventoryProduct", (string)null);
                });

            modelBuilder.Entity("BeYou.Domain.Models.InventoryProductTransaction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<long>("InventoryProductId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "InventoryProductId" }, "IX_InventoryProductTransaction_InventoryProductId");

                    b.ToTable("InventoryProductTransaction", (string)null);
                });

            modelBuilder.Entity("BeYou.Domain.Models.Invoice", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<short>("Number")
                        .HasColumnType("smallint");

                    b.Property<long?>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<long>("PaymentTypeId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("money");

                    b.Property<decimal>("Tax")
                        .HasColumnType("money");

                    b.Property<long>("TaxId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("TaxRate")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("money");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "BranchId" }, "IX_Invoice_BranchId");

                    b.HasIndex(new[] { "CustomerId" }, "IX_Invoice_CustomerId");

                    b.HasIndex(new[] { "OrderId" }, "IX_Invoice_OrderId");

                    b.HasIndex(new[] { "PaymentTypeId" }, "IX_Invoice_PaymentTypeId");

                    b.HasIndex(new[] { "TaxId" }, "IX_Invoice_TaxId");

                    b.ToTable("Invoice", (string)null);
                });

            modelBuilder.Entity("BeYou.Domain.Models.InvoiceDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("InvoiceId")
                        .HasColumnType("bigint");

                    b.Property<byte>("LineNumber")
                        .HasColumnType("tinyint");

                    b.Property<long?>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<short>("Quantity")
                        .HasColumnType("smallint");

                    b.Property<long?>("ServiceId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("money");

                    b.Property<decimal>("Tax")
                        .HasColumnType("money");

                    b.Property<decimal>("Total")
                        .HasColumnType("money");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("money");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "InvoiceId" }, "IX_InvoiceDetail_InvoiceId");

                    b.HasIndex(new[] { "ProductId" }, "IX_InvoiceDetail_ProductId");

                    b.HasIndex(new[] { "ServiceId" }, "IX_InvoiceDetail_ServiceId");

                    b.ToTable("InvoiceDetail", (string)null);
                });

            modelBuilder.Entity("BeYou.Domain.Models.InvoiceDetailProduct", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("InvoiceDetailId")
                        .HasColumnType("bigint");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(6, 2)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "InvoiceDetailId" }, "IX_InvoiceDetailProduct_InvoiceDetailId");

                    b.HasIndex(new[] { "ProductId" }, "IX_InvoiceDetailProduct_ProductId");

                    b.ToTable("InvoiceDetailProduct", (string)null);
                });

            modelBuilder.Entity("BeYou.Domain.Models.Order", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<short>("Number")
                        .HasColumnType("smallint");

                    b.Property<long>("PaymentTypeId")
                        .HasColumnType("bigint");

                    b.Property<long>("ReservationId")
                        .HasColumnType("bigint");

                    b.Property<long>("StatusOrderId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("money");

                    b.Property<decimal>("Tax")
                        .HasColumnType("money");

                    b.Property<long>("TaxId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("TaxRate")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("money");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "BranchId" }, "IX_Order_BranchId");

                    b.HasIndex(new[] { "CustomerId" }, "IX_Order_CustomerId");

                    b.HasIndex(new[] { "PaymentTypeId" }, "IX_Order_PaymentTypeId");

                    b.HasIndex(new[] { "ReservationId" }, "IX_Order_ReservationId");

                    b.HasIndex(new[] { "StatusOrderId" }, "IX_Order_StatusOrderId");

                    b.HasIndex(new[] { "TaxId" }, "IX_Order_TaxId");

                    b.ToTable("Order", (string)null);
                });

            modelBuilder.Entity("BeYou.Domain.Models.OrderDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<byte>("LineNumber")
                        .HasColumnType("tinyint");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<short>("Quantity")
                        .HasColumnType("smallint");

                    b.Property<long?>("ServiceId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("money");

                    b.Property<decimal>("Tax")
                        .HasColumnType("money");

                    b.Property<decimal>("Total")
                        .HasColumnType("money");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("money");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "OrderId" }, "IX_OrderDetail_OrderId");

                    b.HasIndex(new[] { "ProductId" }, "IX_OrderDetail_ProductId");

                    b.HasIndex(new[] { "ServiceId" }, "IX_OrderDetail_ServiceId");

                    b.ToTable("OrderDetail", (string)null);
                });

            modelBuilder.Entity("BeYou.Domain.Models.OrderDetailProduct", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("OrderDetailId")
                        .HasColumnType("bigint");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(6, 2)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "OrderDetailId" }, "IX_OrderDetailProduct_OrderDetailId");

                    b.HasIndex(new[] { "ProductId" }, "IX_OrderDetailProduct_ProductId");

                    b.ToTable("OrderDetailProduct", (string)null);
                });

            modelBuilder.Entity("BeYou.Domain.Models.PaymentType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ReferenceNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("PaymentType", (string)null);
                });

            modelBuilder.Entity("BeYou.Domain.Models.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<decimal>("Price")
                        .HasColumnType("money");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("SKU");

                    b.Property<long>("UnitMeasureId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CategoryId" }, "IX_Producto_CategoryId");

                    b.HasIndex(new[] { "UnitMeasureId" }, "IX_Producto_UnitMeasureId");

                    b.ToTable("Product", (string)null);
                });

            modelBuilder.Entity("BeYou.Domain.Models.Province", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Province", (string)null);
                });

            modelBuilder.Entity("BeYou.Domain.Models.Reservation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("Hour")
                        .HasColumnType("time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasDefaultValue("P")
                        .IsFixedLength();

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "BranchId" }, "IX_Reservation_BranchId");

                    b.HasIndex(new[] { "CustomerId" }, "IX_Reservation_CustomerId");

                    b.ToTable("Reservation", (string)null);
                });

            modelBuilder.Entity("BeYou.Domain.Models.ReservationDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<long>("ReservationId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ServiceId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ProductId" }, "IX_ReservationDetail_ProductId");

                    b.HasIndex(new[] { "ReservationId" }, "IX_ReservationDetail_ReservationId");

                    b.HasIndex(new[] { "ServiceId" }, "IX_ReservationDetail_ServiceId");

                    b.ToTable("ReservationDetail", (string)null);
                });

            modelBuilder.Entity("BeYou.Domain.Models.ReservationQuestion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Answer")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<long>("ReservationId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ReservationId" }, "IX_ReservationQuestion_ReservationId");

                    b.ToTable("ReservationQuestion", (string)null);
                });

            modelBuilder.Entity("BeYou.Domain.Models.Role", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("Id");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("BeYou.Domain.Models.Schedule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("Day")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeOnly>("EndHour")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("StartHour")
                        .HasColumnType("time");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("Id");

                    b.ToTable("Schedule", (string)null);
                });

            modelBuilder.Entity("BeYou.Domain.Models.Service", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Observation")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<decimal>("Price")
                        .HasColumnType("money");

                    b.Property<long>("TypeServiceId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "TypeServiceId" }, "IX_Service_TypeServiceId");

                    b.ToTable("Service", (string)null);
                });

            modelBuilder.Entity("BeYou.Domain.Models.StatusOrder", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.ToTable("StatusOrder", (string)null);
                });

            modelBuilder.Entity("BeYou.Domain.Models.Tax", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValue(new DateTime(2025, 5, 6, 21, 11, 26, 987, DateTimeKind.Unspecified));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)")
                        .HasDefaultValue("");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("Id");

                    b.ToTable("Tax", (string)null);
                });

            modelBuilder.Entity("BeYou.Domain.Models.TokenMaster", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValue(new DateTime(2025, 5, 6, 0, 0, 0, 0, DateTimeKind.Unspecified));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)")
                        .HasDefaultValue("");

                    b.Property<DateTime>("ExpireAt")
                        .HasColumnType("datetime");

                    b.Property<string>("JwtId")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<bool>("Used")
                        .HasColumnType("bit");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "UserId" }, "IX_TokenMaster_UserId");

                    b.ToTable("TokenMaster", (string)null);
                });

            modelBuilder.Entity("BeYou.Domain.Models.TypeService", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<TimeOnly>("BaseDuration")
                        .HasColumnType("time");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TypeService", (string)null);
                });

            modelBuilder.Entity("BeYou.Domain.Models.UnitMeasure", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValue(new DateTime(2025, 5, 6, 21, 11, 27, 299, DateTimeKind.Unspecified));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)")
                        .HasDefaultValue("");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nchar(5)")
                        .IsFixedLength();

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("Id");

                    b.ToTable("UnitMeasure", (string)null);
                });

            modelBuilder.Entity("BeYou.Domain.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Address")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateOnly>("Birthday")
                        .HasColumnType("date");

                    b.Property<string>("CardId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<long>("DistrictId")
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<long>("GenderId")
                        .HasColumnType("bigint");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("ProfilePictureUrl")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.Property<int>("Telephone")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "DistrictId" }, "IX_User_DistrictId");

                    b.HasIndex(new[] { "GenderId" }, "IX_User_GenderId");

                    b.HasIndex(new[] { "RoleId" }, "IX_User_RoleId");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("BeYou.Domain.Models.UserBranch", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "BranchId" }, "IX_UserBranch_BranchId");

                    b.HasIndex(new[] { "UserId" }, "IX_UserBranch_UserId");

                    b.ToTable("UserBranch", (string)null);
                });

            modelBuilder.Entity("BeYou.Domain.Models.Vendor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Address")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<long>("DistrictId")
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FiscalNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("SocialReason")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Telephone")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "DistrictId" }, "IX_Vendor_DistrictId");

                    b.ToTable("Vendor", (string)null);
                });

            modelBuilder.Entity("BeYou.Domain.Models.Branch", b =>
                {
                    b.HasOne("BeYou.Domain.Models.District", "District")
                        .WithMany("Branches")
                        .HasForeignKey("DistrictId")
                        .IsRequired()
                        .HasConstraintName("FK_Branch_District");

                    b.Navigation("District");
                });

            modelBuilder.Entity("BeYou.Domain.Models.BranchHoliday", b =>
                {
                    b.HasOne("BeYou.Domain.Models.Branch", "Branch")
                        .WithMany("BranchHolidays")
                        .HasForeignKey("BranchId")
                        .IsRequired()
                        .HasConstraintName("FK_BranchHoliday_Sucursal");

                    b.HasOne("BeYou.Domain.Models.Holiday", "Holiday")
                        .WithMany("BranchHolidays")
                        .HasForeignKey("HolidayId")
                        .IsRequired()
                        .HasConstraintName("FK_BranchHoliday_Holiday");

                    b.Navigation("Branch");

                    b.Navigation("Holiday");
                });

            modelBuilder.Entity("BeYou.Domain.Models.BranchSchedule", b =>
                {
                    b.HasOne("BeYou.Domain.Models.Branch", "Branch")
                        .WithMany("BranchSchedules")
                        .HasForeignKey("BranchId")
                        .IsRequired()
                        .HasConstraintName("FK_BranchSchedule_Branch");

                    b.HasOne("BeYou.Domain.Models.Schedule", "Schedule")
                        .WithMany("BranchSchedules")
                        .HasForeignKey("ScheduleId")
                        .IsRequired()
                        .HasConstraintName("FK_BranchSchedule_Schedule");

                    b.Navigation("Branch");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("BeYou.Domain.Models.BranchScheduleBlock", b =>
                {
                    b.HasOne("BeYou.Domain.Models.BranchSchedule", "BranchSchedule")
                        .WithMany("BranchScheduleBlocks")
                        .HasForeignKey("BranchScheduleId")
                        .IsRequired()
                        .HasConstraintName("FK_BranchScheduleBlock_BranchSchedule");

                    b.Navigation("BranchSchedule");
                });

            modelBuilder.Entity("BeYou.Domain.Models.Canton", b =>
                {
                    b.HasOne("BeYou.Domain.Models.Province", "Province")
                        .WithMany("Cantons")
                        .HasForeignKey("ProvinceId")
                        .IsRequired()
                        .HasConstraintName("FK_Canton_Province");

                    b.Navigation("Province");
                });

            modelBuilder.Entity("BeYou.Domain.Models.Contact", b =>
                {
                    b.HasOne("BeYou.Domain.Models.Vendor", "Vendor")
                        .WithMany("Contacts")
                        .HasForeignKey("VendorId")
                        .IsRequired()
                        .HasConstraintName("FK_Contact_Vendor");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("BeYou.Domain.Models.Customer", b =>
                {
                    b.HasOne("BeYou.Domain.Models.District", "District")
                        .WithMany("Customers")
                        .HasForeignKey("DistrictId")
                        .IsRequired()
                        .HasConstraintName("FK_Customer_District");

                    b.Navigation("District");
                });

            modelBuilder.Entity("BeYou.Domain.Models.District", b =>
                {
                    b.HasOne("BeYou.Domain.Models.Canton", "Canton")
                        .WithMany("Districts")
                        .HasForeignKey("CantonId")
                        .IsRequired()
                        .HasConstraintName("FK_District_Canton");

                    b.Navigation("Canton");
                });

            modelBuilder.Entity("BeYou.Domain.Models.Inventory", b =>
                {
                    b.HasOne("BeYou.Domain.Models.Branch", "Branch")
                        .WithMany("Inventories")
                        .HasForeignKey("BranchId")
                        .IsRequired()
                        .HasConstraintName("FK_Inventory_Branch");

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("BeYou.Domain.Models.InventoryProduct", b =>
                {
                    b.HasOne("BeYou.Domain.Models.Product", "IdProductoNavigation")
                        .WithMany("InventoryProducts")
                        .HasForeignKey("IdProducto")
                        .IsRequired()
                        .HasConstraintName("FK_InventoryProduct_Product");

                    b.HasOne("BeYou.Domain.Models.Inventory", "Inventory")
                        .WithMany("InventoryProducts")
                        .HasForeignKey("InventoryId")
                        .IsRequired()
                        .HasConstraintName("FK_InventoryProduct_Inventory");

                    b.Navigation("IdProductoNavigation");

                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("BeYou.Domain.Models.InventoryProductTransaction", b =>
                {
                    b.HasOne("BeYou.Domain.Models.InventoryProduct", "InventoryProduct")
                        .WithMany("InventoryProductTransactions")
                        .HasForeignKey("InventoryProductId")
                        .IsRequired()
                        .HasConstraintName("FK_InventoryProductTransaction_InventoryProduct");

                    b.Navigation("InventoryProduct");
                });

            modelBuilder.Entity("BeYou.Domain.Models.Invoice", b =>
                {
                    b.HasOne("BeYou.Domain.Models.Branch", "Branch")
                        .WithMany("Invoices")
                        .HasForeignKey("BranchId")
                        .IsRequired()
                        .HasConstraintName("FK_Invoice_Branch");

                    b.HasOne("BeYou.Domain.Models.Customer", "Customer")
                        .WithMany("Invoices")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("FK_Invoice_Customer");

                    b.HasOne("BeYou.Domain.Models.Order", "Order")
                        .WithMany("Invoices")
                        .HasForeignKey("OrderId")
                        .HasConstraintName("FK_Invoice_Order");

                    b.HasOne("BeYou.Domain.Models.PaymentType", "PaymentType")
                        .WithMany("Invoices")
                        .HasForeignKey("PaymentTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_Invoice_PaymentType");

                    b.HasOne("BeYou.Domain.Models.Tax", "TaxNavigation")
                        .WithMany("Invoices")
                        .HasForeignKey("TaxId")
                        .IsRequired()
                        .HasConstraintName("FK_Invoice_Tax");

                    b.Navigation("Branch");

                    b.Navigation("Customer");

                    b.Navigation("Order");

                    b.Navigation("PaymentType");

                    b.Navigation("TaxNavigation");
                });

            modelBuilder.Entity("BeYou.Domain.Models.InvoiceDetail", b =>
                {
                    b.HasOne("BeYou.Domain.Models.Invoice", "Invoice")
                        .WithMany("InvoiceDetails")
                        .HasForeignKey("InvoiceId")
                        .IsRequired()
                        .HasConstraintName("FK_InvoiceDetail_Invoice");

                    b.HasOne("BeYou.Domain.Models.Product", "Product")
                        .WithMany("InvoiceDetails")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("FK_InvoiceDetail_Product");

                    b.HasOne("BeYou.Domain.Models.Service", "Service")
                        .WithMany("InvoiceDetails")
                        .HasForeignKey("ServiceId")
                        .HasConstraintName("FK_InvoiceDetail_Service");

                    b.Navigation("Invoice");

                    b.Navigation("Product");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("BeYou.Domain.Models.InvoiceDetailProduct", b =>
                {
                    b.HasOne("BeYou.Domain.Models.InvoiceDetail", "InvoiceDetail")
                        .WithMany("InvoiceDetailProducts")
                        .HasForeignKey("InvoiceDetailId")
                        .IsRequired()
                        .HasConstraintName("FK_InvoiceDetailProduct_InvoiceDetail");

                    b.HasOne("BeYou.Domain.Models.Product", "Product")
                        .WithMany("InvoiceDetailProducts")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK_InvoiceDetailProduct_Product");

                    b.Navigation("InvoiceDetail");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BeYou.Domain.Models.Order", b =>
                {
                    b.HasOne("BeYou.Domain.Models.Branch", "Branch")
                        .WithMany("Orders")
                        .HasForeignKey("BranchId")
                        .IsRequired()
                        .HasConstraintName("FK_Order_Branch");

                    b.HasOne("BeYou.Domain.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("FK_Order_Customer");

                    b.HasOne("BeYou.Domain.Models.PaymentType", "PaymentType")
                        .WithMany("Orders")
                        .HasForeignKey("PaymentTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_Order_PaymentType");

                    b.HasOne("BeYou.Domain.Models.Reservation", "Reservation")
                        .WithMany("Orders")
                        .HasForeignKey("ReservationId")
                        .IsRequired()
                        .HasConstraintName("FK_Order_Reservation");

                    b.HasOne("BeYou.Domain.Models.StatusOrder", "StatusOrder")
                        .WithMany("Orders")
                        .HasForeignKey("StatusOrderId")
                        .IsRequired()
                        .HasConstraintName("FK_Order_StatusOrder");

                    b.HasOne("BeYou.Domain.Models.Tax", "TaxNavigation")
                        .WithMany("Orders")
                        .HasForeignKey("TaxId")
                        .IsRequired()
                        .HasConstraintName("FK_Order_Tax");

                    b.Navigation("Branch");

                    b.Navigation("Customer");

                    b.Navigation("PaymentType");

                    b.Navigation("Reservation");

                    b.Navigation("StatusOrder");

                    b.Navigation("TaxNavigation");
                });

            modelBuilder.Entity("BeYou.Domain.Models.OrderDetail", b =>
                {
                    b.HasOne("BeYou.Domain.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("FK_OrderDetail_Order");

                    b.HasOne("BeYou.Domain.Models.Product", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("FK_OrderDetail_Product");

                    b.HasOne("BeYou.Domain.Models.Service", "Service")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ServiceId")
                        .HasConstraintName("FK_OrderDetail_Service");

                    b.Navigation("Order");

                    b.Navigation("Product");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("BeYou.Domain.Models.OrderDetailProduct", b =>
                {
                    b.HasOne("BeYou.Domain.Models.OrderDetail", "OrderDetail")
                        .WithMany("OrderDetailProducts")
                        .HasForeignKey("OrderDetailId")
                        .IsRequired()
                        .HasConstraintName("FK_OrderDetailProduct_OrderDetail");

                    b.HasOne("BeYou.Domain.Models.Product", "Product")
                        .WithMany("OrderDetailProducts")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK_OrderDetailProduct_Product");

                    b.Navigation("OrderDetail");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BeYou.Domain.Models.Product", b =>
                {
                    b.HasOne("BeYou.Domain.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("FK_Product_Category");

                    b.HasOne("BeYou.Domain.Models.UnitMeasure", "UnitMeasure")
                        .WithMany("Products")
                        .HasForeignKey("UnitMeasureId")
                        .IsRequired()
                        .HasConstraintName("FK_Product_UnitMeasure");

                    b.Navigation("Category");

                    b.Navigation("UnitMeasure");
                });

            modelBuilder.Entity("BeYou.Domain.Models.Reservation", b =>
                {
                    b.HasOne("BeYou.Domain.Models.Branch", "Branch")
                        .WithMany("Reservations")
                        .HasForeignKey("BranchId")
                        .IsRequired()
                        .HasConstraintName("FK_Reservation_Branch");

                    b.HasOne("BeYou.Domain.Models.Customer", "Customer")
                        .WithMany("Reservations")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("FK_Reservation_Customer");

                    b.Navigation("Branch");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("BeYou.Domain.Models.ReservationDetail", b =>
                {
                    b.HasOne("BeYou.Domain.Models.Product", "Product")
                        .WithMany("ReservationDetails")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("FK_ReservationDetail_Product");

                    b.HasOne("BeYou.Domain.Models.Reservation", "Reservation")
                        .WithMany("ReservationDetails")
                        .HasForeignKey("ReservationId")
                        .IsRequired()
                        .HasConstraintName("FK_ReservationDetail_Reservation");

                    b.HasOne("BeYou.Domain.Models.Service", "Service")
                        .WithMany("ReservationDetails")
                        .HasForeignKey("ServiceId")
                        .HasConstraintName("FK_ReservationDetail_Service");

                    b.Navigation("Product");

                    b.Navigation("Reservation");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("BeYou.Domain.Models.ReservationQuestion", b =>
                {
                    b.HasOne("BeYou.Domain.Models.Reservation", "Reservation")
                        .WithMany("ReservationQuestions")
                        .HasForeignKey("ReservationId")
                        .IsRequired()
                        .HasConstraintName("FK_ReservationQuestion_Reservation");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("BeYou.Domain.Models.Service", b =>
                {
                    b.HasOne("BeYou.Domain.Models.TypeService", "TypeService")
                        .WithMany("Services")
                        .HasForeignKey("TypeServiceId")
                        .IsRequired()
                        .HasConstraintName("FK_Service_TypeService");

                    b.Navigation("TypeService");
                });

            modelBuilder.Entity("BeYou.Domain.Models.TokenMaster", b =>
                {
                    b.HasOne("BeYou.Domain.Models.User", "User")
                        .WithMany("TokenMasters")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_TokenMaster_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BeYou.Domain.Models.User", b =>
                {
                    b.HasOne("BeYou.Domain.Models.District", "District")
                        .WithMany("Users")
                        .HasForeignKey("DistrictId")
                        .IsRequired()
                        .HasConstraintName("FK_User_District");

                    b.HasOne("BeYou.Domain.Models.Gender", "Gender")
                        .WithMany("Users")
                        .HasForeignKey("GenderId")
                        .IsRequired()
                        .HasConstraintName("FK_User_Gender");

                    b.HasOne("BeYou.Domain.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK_User_Role");

                    b.Navigation("District");

                    b.Navigation("Gender");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("BeYou.Domain.Models.UserBranch", b =>
                {
                    b.HasOne("BeYou.Domain.Models.Branch", "Branch")
                        .WithMany("UserBranches")
                        .HasForeignKey("BranchId")
                        .IsRequired()
                        .HasConstraintName("FK_UserBranch_Branch");

                    b.HasOne("BeYou.Domain.Models.User", "User")
                        .WithMany("UserBranches")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_UserBranch_User");

                    b.Navigation("Branch");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BeYou.Domain.Models.Vendor", b =>
                {
                    b.HasOne("BeYou.Domain.Models.District", "District")
                        .WithMany("Vendors")
                        .HasForeignKey("DistrictId")
                        .IsRequired()
                        .HasConstraintName("FK_Vendor_District");

                    b.Navigation("District");
                });

            modelBuilder.Entity("BeYou.Domain.Models.Branch", b =>
                {
                    b.Navigation("BranchHolidays");

                    b.Navigation("BranchSchedules");

                    b.Navigation("Inventories");

                    b.Navigation("Invoices");

                    b.Navigation("Orders");

                    b.Navigation("Reservations");

                    b.Navigation("UserBranches");
                });

            modelBuilder.Entity("BeYou.Domain.Models.BranchSchedule", b =>
                {
                    b.Navigation("BranchScheduleBlocks");
                });

            modelBuilder.Entity("BeYou.Domain.Models.Canton", b =>
                {
                    b.Navigation("Districts");
                });

            modelBuilder.Entity("BeYou.Domain.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("BeYou.Domain.Models.Customer", b =>
                {
                    b.Navigation("Invoices");

                    b.Navigation("Orders");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("BeYou.Domain.Models.District", b =>
                {
                    b.Navigation("Branches");

                    b.Navigation("Customers");

                    b.Navigation("Users");

                    b.Navigation("Vendors");
                });

            modelBuilder.Entity("BeYou.Domain.Models.Gender", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("BeYou.Domain.Models.Holiday", b =>
                {
                    b.Navigation("BranchHolidays");
                });

            modelBuilder.Entity("BeYou.Domain.Models.Inventory", b =>
                {
                    b.Navigation("InventoryProducts");
                });

            modelBuilder.Entity("BeYou.Domain.Models.InventoryProduct", b =>
                {
                    b.Navigation("InventoryProductTransactions");
                });

            modelBuilder.Entity("BeYou.Domain.Models.Invoice", b =>
                {
                    b.Navigation("InvoiceDetails");
                });

            modelBuilder.Entity("BeYou.Domain.Models.InvoiceDetail", b =>
                {
                    b.Navigation("InvoiceDetailProducts");
                });

            modelBuilder.Entity("BeYou.Domain.Models.Order", b =>
                {
                    b.Navigation("Invoices");

                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("BeYou.Domain.Models.OrderDetail", b =>
                {
                    b.Navigation("OrderDetailProducts");
                });

            modelBuilder.Entity("BeYou.Domain.Models.PaymentType", b =>
                {
                    b.Navigation("Invoices");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("BeYou.Domain.Models.Product", b =>
                {
                    b.Navigation("InventoryProducts");

                    b.Navigation("InvoiceDetailProducts");

                    b.Navigation("InvoiceDetails");

                    b.Navigation("OrderDetailProducts");

                    b.Navigation("OrderDetails");

                    b.Navigation("ReservationDetails");
                });

            modelBuilder.Entity("BeYou.Domain.Models.Province", b =>
                {
                    b.Navigation("Cantons");
                });

            modelBuilder.Entity("BeYou.Domain.Models.Reservation", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("ReservationDetails");

                    b.Navigation("ReservationQuestions");
                });

            modelBuilder.Entity("BeYou.Domain.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("BeYou.Domain.Models.Schedule", b =>
                {
                    b.Navigation("BranchSchedules");
                });

            modelBuilder.Entity("BeYou.Domain.Models.Service", b =>
                {
                    b.Navigation("InvoiceDetails");

                    b.Navigation("OrderDetails");

                    b.Navigation("ReservationDetails");
                });

            modelBuilder.Entity("BeYou.Domain.Models.StatusOrder", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("BeYou.Domain.Models.Tax", b =>
                {
                    b.Navigation("Invoices");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("BeYou.Domain.Models.TypeService", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("BeYou.Domain.Models.UnitMeasure", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("BeYou.Domain.Models.User", b =>
                {
                    b.Navigation("TokenMasters");

                    b.Navigation("UserBranches");
                });

            modelBuilder.Entity("BeYou.Domain.Models.Vendor", b =>
                {
                    b.Navigation("Contacts");
                });
#pragma warning restore 612, 618
        }
    }
}
